#!/bin/bash

set -e

echo "\033[32mRunning \033[1msudo apt update...\033[0m"
sudo apt update -y
echo "\033[32mDownloading necessary files...\033[0m"
mkdir -p /tmp/avalanche
wget -P /tmp/avalanche https://gitea.thebrokenrail.com/minecraft-pi-reborn/minecraft-pi-reborn/releases/download/3.0.3/minecraft-pi-reborn-3.0.3-amd64.deb
echo "\033[32mInstalling the packages...\033[0m"
sudo apt install /tmp/avalanche/minecraft-pi-reborn-3.0.3-amd64.deb -y
echo "\033[32mCleaning up...\033[0m"
rm -rf /tmp/avalanche
