#!/bin/bash

set -e

echo "\033[32mRunning \033[1msudo apt update...\033[0m"
sudo apt update -y
echo "\033[32mDownloading necessary files...\033[0m"
mkdir -p /tmp/avalanche
wget -P /tmp/avalanche https://raw.githubusercontent.com/Gabyface910/debiancity2000/refs/heads/main/sc2000.deb
echo "\033[32mInstalling the packages...\033[0m"
sudo apt install /tmp/avalanche/sc2000.deb -y
echo "\033[32mCleaning up...\033[0m"
rm -rf /tmp/avalanche
echo "\033[32mMaking executable...\033[0m"
chmod +x /usr/games/simcity
chmod -R +w /usr/share/simcity2000
chmod -R +x /usr/share/simcity2000
