#!/bin/bash

set -e

echo "\033[32mRunning \033[1msudo apt update...\033[0m"
sudo apt update -y
echo "\033[32mDownloading necessary files...\033[0m"
mkdir -p /tmp/avalanche
wget -P /tmp/avalanche https://github.com/Gabyface910/windows-95-deb/releases/download/v0.1.0/windows-95.deb
echo "\033[32mInstalling the packages...\033[0m"
sudo apt install /tmp/avalanche/windows-95.deb -y
echo "\033[32mCleaning up...\033[0m"
rm -rf /tmp/avalanche
echo "\033[32mMaking executable...\033[0m"
chmod +x /usr/local/bin/windows-95
chmod -R +w /usr/share/windows-95
chmod -R +x /usr/share/windows-95
